export const PATHS = {
  ELEMENTS: {
    ROOT: "/elements",
    ACCORDION: "/elements/accordion",
    ALERT: "/elements/alert",
    APP_BAR: "/elements/app-bar",
    AUTOCOMPLETE: "/elements/autocomplete",
    AVATAR: "/elements/avatar",
    BACKDROP: "/elements/backdrop",
    BADGE: "/elements/badge",
    BREADCRUMB: "/elements/breadcrumb",
    BUTTON: "/elements/button",
    BUTTON_GROUP: "/elements/button-group",
    BUTTON_NAVIGATION: "/elements/button-navigation",
    CARD: "/elements/card",
    CHECKBOX: "/elements/checkbox",
    CHIP: "/elements/chip",
    DIALOG: "/elements/dialog",
    DIVIDER: "/elements/divider",
    DRAWER: "/elements/drawer",
    FLOATING_ACTION_BUTTON: "/elements/floating-action-button",
    GRID: "/elements/grid",
    IMAGE_LIST: "/elements/image-list",
    LIST: "/elements/list",
    MENU: "/elements/menu",
    MODAL: "/elements/modal",
    PAGINATION: "/elements/pagination",
    PAPER: "/elements/paper",
    POPOVER: "/elements/popover",
    PROGRESS: "/elements/progress",
    RADIO_GROUP: "/elements/radio-group",
    RATING: "/elements/rating",
    SELECT: "/elements/select",
    SKELETON: "/elements/skeleton",
    SLIDER: "/elements/slider",
    SPEED_DIAL: "/elements/speed-dial",
    STEPPER: "/elements/stepper",
    SWITCH: "/elements/switch",
    TABLE: "/elements/table",
    TABS: "/elements/tabs",
    TEXT_FIELD: "/elements/text-field",
    TEXTAREA: "/elements/textarea",
    TOGGLE_BUTTON: "/elements/toggle-button",
    TOOLTIP: "/elements/tooltip",
    TRANSFER_LIST: "/elements/transfer-list",
    TYPOGRAPHY: "/elements/typography",
  },
  DOCS: {
    ROOT: "/docs",
    INTRO: "/docs/intro",
    INSTALL: "/docs/installation",
  },
  BLOCKS: {
    ROOT: "/blocks",
  },
  TEMPLATES: {
    ROOT: "/templates",
  },
  DASHBOARD: {
    ROOT: "/dashboard",
  },
  FORM: {
    ROOT: "/form",
  },
  CONTRIBUTE: "/contribute",
};
