import { PATHS } from "@/router/paths";

export const blockArr = [
  { label: "About", path: PATHS.BLOCKS.ABOUT },
  { label: "Call To Action", path: PATHS.BLOCKS.CALL_TO_ACTION },
  { label: "Contact", path: PATHS.BLOCKS.CONTACT },
  { label: "Copyright", path: PATHS.BLOCKS.COPYRIGHT },
  { label: "FAQ", path: PATHS.BLOCKS.FAQ },
  { label: "Feature & Benefit", path: PATHS.BLOCKS.FEATURE_AND_BENEFIT },
  { label: "Feature Product", path: PATHS.BLOCKS.FEATURE_PRODUCT },
  { label: "Focus Boxes", path: PATHS.BLOCKS.FOCUS_BOXES },
  { label: "Footer", path: PATHS.BLOCKS.FOOTER },
  { label: "Header", path: PATHS.BLOCKS.HEADER },
  { label: "Hero", path: PATHS.BLOCKS.HERO },
  { label: "Image Gallery", path: PATHS.BLOCKS.IMAGE_GALLERY },
  { label: "Logo Grid", path: PATHS.BLOCKS.LOGO_GRID },
  { label: "Map", path: PATHS.BLOCKS.MAP },
  { label: "New Letter Subscription", path: PATHS.BLOCKS.NEW_LETTER_SUBSCRIPTION },
  { label: "Popup", path: PATHS.BLOCKS.POPUP },
  { label: "Pricing Menu", path: PATHS.BLOCKS.PRICING_MENU },
  { label: "Pricing Table", path: PATHS.BLOCKS.PRICING_TABLE },
  { label: "Services", path: PATHS.BLOCKS.SERVICES },
  { label: "Single Profile", path: PATHS.BLOCKS.SINGLE_PROFILE },
  { label: "Single Quote/ pull", path: PATHS.BLOCKS.SINGLE_QUOTE_PULL },
  { label: "Sub Hero", path: PATHS.BLOCKS.SUB_HERO },
  { label: "Team", path: PATHS.BLOCKS.TEAM },
  { label: "Testimonial Grid", path: PATHS.BLOCKS.TESTIMONIAL_GRID },
  { label: "Testimonial Slider", path: PATHS.BLOCKS.TESTIMONIAL_SLIDER },
].sort((a, b) => a.label.localeCompare(b.label));
